more WIP

diff --git a/packages/bootstrap/stage3/Containerfile b/packages/bootstrap/stage3/Containerfile
--- a/packages/bootstrap/stage3/Containerfile
+++ b/packages/bootstrap/stage3/Containerfile
@@ -18,24 +18,184 @@ COPY <<-'EOF' /etc/profile
 	export SOURCE_DATE_EPOCH=1
 	export KCONFIG_NOTIMESTAMP=1
 EOF
-SHELL ["/bin/sh","-l","-c"]
+SHELL ["/bin/sh","-l","-c","-e","-u","-x"]
 
 ARG MUSL_VERSION
 ADD fetch/musl-${MUSL_VERSION}.tar.gz /
 WORKDIR /musl-${MUSL_VERSION}
 RUN --network=none <<-EOF
-	set -eux
 	./configure \
 		--prefix=/usr \
 		--host=${TARGET}
+	make
 	make DESTDIR=/rootfs install
+	mkdir -p /rootfs/usr/bin /rootfs/usr/lib
+	rm -rf /rootfs/lib
+	ln -sf /usr/lib/ld-musl-${ARCH}.so.1 /rootfs/usr/bin/ldd
+	mv -f /rootfs/usr/lib/libc.so /rootfs/usr/lib/ld-musl-${ARCH}.so.1
+	ln -sf ld-musl-${ARCH}.so.1 /rootfs/usr/lib/libc.musl-${ARCH}.so.1
+	ln -sf /usr/lib/ld-musl-${ARCH}.so.1 /rootfs/usr/lib/libc.so
+EOF
+
+ARG BINUTILS_VERSION
+ADD fetch/binutils-${BINUTILS_VERSION}.tar.xz /
+WORKDIR /binutils-${BINUTILS_VERSION}
+RUN --network=none <<-EOF
+	./configure \
+		--host=${TARGET} \
+		--build=${BUILD} \
+		--prefix=/usr \
+		--bindir=/usr/bin \
+		--mandir=/usr/share/man \
+		--infodir=/usr/share/info \
+		--sysconfdir=/etc \
+		--disable-nls \
+		--disable-multilib \
+		--disable-plugins \
+		--disable-gprofng \
+		--enable-64-bit-bfd \
+		--enable-ld=default \
+		--enable-install-libiberty \
+		--enable-deterministic-archives
+	make
+	make DESTDIR=/rootfs install
+EOF
+
+ARG MAKE_VERSION
+ADD fetch/make-${MAKE_VERSION}.tar.gz /
+WORKDIR /make-${MAKE_VERSION}
+RUN --network=none <<-EOF
+	./configure \
+		--build=${BUILD} \
+		--host=${TARGET} \
+		--prefix=/usr \
+		--mandir=/usr/share/man \
+		--infodir=/usr/share/info \
+		--disable-nls
+	make
+	make DESTDIR=/rootfs install
+EOF
+
+ARG GCC_VERSION
+ARG GMP_VERSION
+ARG MPC_VERSION
+ARG MPFR_VERSION
+ARG ISL_VERSION
+ADD fetch/gcc-${GCC_VERSION}.tar.xz /
+ADD fetch/gmp-${GMP_VERSION}.tar.bz2 /
+ADD fetch/mpc-${MPC_VERSION}.tar.gz /
+ADD fetch/mpfr-${MPFR_VERSION}.tar.bz2 /
+ADD fetch/isl-${ISL_VERSION}.tar.bz2 /
+WORKDIR /gcc-${GCC_VERSION}
+RUN --network=none <<-EOF
+	mv ../gmp-${GMP_VERSION} gmp
+	mv ../mpfr-${MPFR_VERSION} mpfr
+	mv ../mpc-${MPC_VERSION} mpc
+	mv ../isl-${ISL_VERSION} isl
+	./configure \
+		--build=${BUILD} \
+		--host=${TARGET} \
+		--target=${TARGET} \
+		--prefix=/usr \
+		--mandir=/usr/share/man \
+		--infodir=/usr/share/info \
+		--libdir=/usr/lib \
+		--disable-cet \
+		--disable-fixed-point \
+		--disable-libstdcxx-pch \
+		--disable-multilib \
+		--disable-libsanitizer \
+		--disable-nls \
+		--disable-werror \
+		--enable-__cxa_atexit \
+		--enable-default-pie \
+		--enable-default-ssp \
+		--enable-languages=c,c++ \
+		--enable-link-serialization=2 \
+		--enable-linker-build-id
+	make
+	make DESTDIR=/rootfs install
+EOF
+
+ARG BUSYBOX_VERSION
+ADD fetch/busybox-${BUSYBOX_VERSION}.tar.bz2 /
+WORKDIR /busybox-${BUSYBOX_VERSION}/build
+RUN --network=none <<-EOF
+	setConfs='
+		CONFIG_LAST_SUPPORTED_WCHAR=0
+		CONFIG_STATIC=y
+	'
+	unsetConfs='
+		CONFIG_FEATURE_SYNC_FANCY
+		CONFIG_FEATURE_HAVE_RPC
+		CONFIG_FEATURE_INETD_RPC
+		CONFIG_FEATURE_UTMP
+		CONFIG_FEATURE_WTMP
+	'
+	make \
+		-f ../Makefile \
+		KBUILD_SRC=../ \
+		CROSS_COMPILE=${TARGET}- \
+		defconfig
+	for conf in $unsetConfs; do
+		sed -i \
+			-e "s!^$conf=.*\$!# $conf is not set!" \
+			.config
+	done
+	for confV in $setConfs; do
+		conf="${confV%=*}"
+		sed -i \
+			-e "s!^$conf=.*\$!$confV!" \
+			-e "s!^# $conf is not set\$!$confV!" \
+			.config
+		if ! grep -q "^$confV\$" .config; then
+			echo "$confV" >> .config
+		fi
+	done
+	make oldconfig CROSS_COMPILE=${TARGET}-
+	for conf in $unsetConfs; do
+		! grep -q "^$conf=" .config
+	done
+	for confV in $setConfs; do
+		grep -q "^$confV\$" .config
+	done
+	make CROSS_COMPILE=${TARGET}-
+	make \
+		CROSS_COMPILE=${TARGET}- \
+		CONFIG_PREFIX=/rootfs \
+		install
+EOF
+
+ARG LINUX_VERSION
+ADD fetch/linux-${LINUX_VERSION}.tar.xz /
+WORKDIR /linux-${LINUX_VERSION}
+RUN --network=none <<-EOF
+	make ARCH="$(echo ${TARGETARCH} | sed 's/amd64/x86_64/')" headers
+	find usr/include -name '.*' -delete
+	rm usr/include/Makefile
+	rm usr/include/headers_check.pl
+	cp -rv usr/include/* /rootfs/usr/include/
+EOF
+
+ARG GO_VERSION
+ADD fetch/go${GO_VERSION}.src.tar.gz /
+WORKDIR /go/src
+RUN --network=none <<-EOF
+	GOROOT_BOOTSTRAP=/usr/lib/go \
+	GOHOSTARCH=386 \
+	GOARCH=${TARGETARCH} \
+	bash -- make.bash
+	rm -rf testdata
+	install -D -t /rootfs/usr/lib/go/bin ../bin/linux_${TARGETARCH}/*
+	cp -r ../lib ../pkg ../src /rootfs/usr/lib/go/
+	ln -s /usr/lib/go/bin/go /rootfs/usr/bin/go
+	ln -s /usr/lib/go/bin/gofmt /rootfs/usr/bin/gofmt
 EOF
 
 ARG XZ_VERSION
 ADD fetch/xz-${XZ_VERSION}.tar.gz /
 WORKDIR /xz-${XZ_VERSION}
 RUN --network=none <<-EOF
-	set -eux
 	autoreconf -fi
 	./configure \
 		--prefix=/usr \
@@ -47,7 +207,6 @@ ARG LIBUCONTEXT_VERSION
 ADD fetch/libucontext-${LIBUCONTEXT_VERSION}.tar.gz /
 WORKDIR /libucontext-libucontext-${LIBUCONTEXT_VERSION}
 RUN --network=none <<-EOF
-	set -eux
 	export CC=${ARCH}-linux-musl-gcc
 	make ARCH=${ARCH} DESTDIR=/rootfs install
 EOF
@@ -56,10 +215,6 @@ ARG LIBUNWIND_VERSION
 ADD fetch/libunwind-${LIBUNWIND_VERSION}.tar.gz /
 WORKDIR /libunwind-${LIBUNWIND_VERSION}
 RUN <<-EOF
-	set -eux
-	export CFLAGS="-I/rootfs/usr/include -L/rootfs/usr/lib -L/usr/lib -L/lib -llzma -lucontext"
-	export CXXFLAGS="$CFLAGS"
-	export CPPFLAGS="$CFLAGS"
 	autoreconf -i
 	./configure \
 		--prefix=/usr \
@@ -73,147 +228,20 @@ ARG CMAKE_VERSION
 ADD fetch/cmake-${CMAKE_VERSION}.tar.gz /
 WORKDIR /cmake-${CMAKE_VERSION}/build
 RUN --network=none <<-EOF
-	set -eux
-	export CXXFLAGS="-latomic"
 	../configure \
 		--prefix=/usr \
 		--no-system-cppdap \
 		--no-system-curl \
 		-- \
+		-DCMAKE_C_COMPILER=${ARCH}-linux-musl-gcc \
+		-DCMAKE_CXX_COMPILER=${ARCH}-linux-musl-gcc \
 		-DCMAKE_USE_OPENSSL=OFF
+	cat /cmake-3.31.5/build/Bootstrap.cmk/cmake_bootstrap.log | grep -B50 -A50 "failed"
 	make
 	make DESTDIR=/rootfs install
 EOF
 
-ARG LLVM_VERSION
-ADD fetch/llvm-${LLVM_VERSION}.tar.xz /
-WORKDIR /llvm-project-${LLVM_VERSION}.src
 RUN --network=none <<-EOF
-	set -eux
-	export PATH=/rootfs/usr/bin:/usr/bin:/usr/sbin
-  export CC="gcc -m32"
-  export CXX="g++ -m32"
-	export CFLAGS=-m32
-	export CXXFLAGS=-m32
-	export LDFLAGS=-m32
-	cmake \
-		-B build \
-		-S llvm \
-		-Wno-dev \
-		-DCMAKE_INSTALL_PREFIX=/usr/ \
-		-DCMAKE_BUILD_TYPE=Release \
-		-DLLVM_TARGETS_TO_BUILD="$LLVM_TARGETS" \
-		-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" \
-		-DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
-		-DLLVM_BUILD_DOCS=OFF
-#-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld"
-	cmake --build build --parallel $(nproc)
-	DESTDIR="/rootfs" cmake --install build
-EOF
-
-ARG MAKE_VERSION
-ADD fetch/make-${MAKE_VERSION}.tar.gz /
-WORKDIR /make-${MAKE_VERSION}
-RUN --network=none <<-EOF
-	set -eux
-	../make-${MAKE_VERSION}/configure \
-		--build=${BUILD} \
-		--host=${TARGET} \
-		--prefix=/usr \
-		--mandir=/usr/share/man \
-		--infodir=/usr/share/info \
-		--disable-nls
-	make -j$(nproc)
-	make DESTDIR=/rootfs install
-EOF
-
-ARG BUSYBOX_VERSION
-ADD fetch/busybox-${BUSYBOX_VERSION}.tar.bz2 /
-WORKDIR /busybox-${BUSYBOX_VERSION}/build
-RUN --network=none <<-EOF
-    set -eux
-    setConfs='
-        CONFIG_LAST_SUPPORTED_WCHAR=0
-        CONFIG_STATIC=y
-    '
-    unsetConfs='
-        CONFIG_FEATURE_SYNC_FANCY
-        CONFIG_FEATURE_HAVE_RPC
-        CONFIG_FEATURE_INETD_RPC
-        CONFIG_FEATURE_UTMP
-        CONFIG_FEATURE_WTMP
-    '
-    make \
-        -f ../Makefile \
-        KBUILD_SRC=../ \
-        CROSS_COMPILE=${TARGET}- \
-        defconfig
-    for conf in $unsetConfs; do
-        sed -i \
-            -e "s!^$conf=.*\$!# $conf is not set!" \
-            .config
-    done
-    for confV in $setConfs; do
-        conf="${confV%=*}"
-        sed -i \
-            -e "s!^$conf=.*\$!$confV!" \
-            -e "s!^# $conf is not set\$!$confV!" \
-            .config
-        if ! grep -q "^$confV\$" .config; then
-            echo "$confV" >> .config
-        fi
-    done
-    make oldconfig CROSS_COMPILE=${TARGET}-
-    for conf in $unsetConfs; do
-        ! grep -q "^$conf=" .config
-    done
-    for confV in $setConfs; do
-        grep -q "^$confV\$" .config
-    done
-    make -j$(nproc) CROSS_COMPILE=${TARGET}-
-EOF
-
-WORKDIR /linux-${LINUX_VERSION}
-RUN --network=none <<-EOF
-	set -eux
-	make ARCH="$(echo ${TARGETARCH} | sed 's/amd64/x86_64/')" headers
-	find usr/include -name '.*' -delete
-	rm usr/include/Makefile
-	rm usr/include/headers_check.pl
-	cp -rv usr/include /build-linux
-EOF
-
-WORKDIR ${HOME}/go
-RUN --network=none <<-EOF
-	set -eux
-	cd src
-	GOROOT_BOOTSTRAP=/usr/lib/go \
-	GOHOSTARCH=386 GOARCH=${TARGETARCH} \
-	bash -- make.bash
-EOF
-RUN --network=none <<-EOF
-	set -eux
-	rm -rf src/testdata
-	mkdir -p /rootfs/usr/lib/go
-	cp bin/linux_${TARGETARCH}/* bin
-	rm -rf bin/linux_${TARGETARCH}
-	cp -a bin lib pkg src /rootfs/usr/lib/go
-	mkdir -p /rootfs/usr/bin
-	ln -s /usr/lib/go/bin/go /rootfs/usr/bin/go
-	ln -s /usr/lib/go/bin/gofmt /rootfs/usr/bin/gofmt
-EOF
-RUN --network=none <<-EOF
-	set -eux
-	. /.env
-	env -C /build-busybox make \
-		CROSS_COMPILE=${TARGET}- \
-		CONFIG_PREFIX=/rootfs \
-		install
-	env -C /build-musl make DESTDIR=/rootfs install
-	env -C /build-binutils make DESTDIR=/rootfs install
-	env -C /build-make make DESTDIR=/rootfs install
-	env -C /build-gcc make DESTDIR=/rootfs install
-	cp -Rv /build-linux/* /rootfs/usr/include/
 	cd /rootfs/
 	ln -sT /lib lib64
 	mkdir -p etc tmp var/tmp
